# Generated by Django 4.0.5 on 2022-06-14 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mc_donalds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='in_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mc_donalds.order'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mc_donalds.product'),
        ),
    ]
